-- 匯入模擬考:九年級第一次模擬考（九年級上學期）

-- 確保班級存在
insert into classes (name) values ('901') on conflict (name) do nothing;
insert into classes (name) values ('902') on conflict (name) do nothing;

-- 依姓名比對學生:找得到就更新班級/座號,找不到就當新生新增
update students set class_id=(select id from classes where name='901'), seat_no='01' where name='許育霖';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '01', '許育霖' where not exists (select 1 from students where name='許育霖');
update students set class_id=(select id from classes where name='901'), seat_no='02' where name='林楷程';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '02', '林楷程' where not exists (select 1 from students where name='林楷程');
update students set class_id=(select id from classes where name='901'), seat_no='03' where name='黃渟維';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '03', '黃渟維' where not exists (select 1 from students where name='黃渟維');
update students set class_id=(select id from classes where name='901'), seat_no='04' where name='黃壬辰';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '04', '黃壬辰' where not exists (select 1 from students where name='黃壬辰');
update students set class_id=(select id from classes where name='901'), seat_no='05' where name='倪楷崴';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '05', '倪楷崴' where not exists (select 1 from students where name='倪楷崴');
update students set class_id=(select id from classes where name='901'), seat_no='07' where name='賴東廷';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '07', '賴東廷' where not exists (select 1 from students where name='賴東廷');
update students set class_id=(select id from classes where name='901'), seat_no='16' where name='邱柏諺';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '16', '邱柏諺' where not exists (select 1 from students where name='邱柏諺');
update students set class_id=(select id from classes where name='901'), seat_no='20' where name='簡廷諭';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '20', '簡廷諭' where not exists (select 1 from students where name='簡廷諭');
update students set class_id=(select id from classes where name='901'), seat_no='22' where name='陳禹彤';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '22', '陳禹彤' where not exists (select 1 from students where name='陳禹彤');
update students set class_id=(select id from classes where name='901'), seat_no='24' where name='陳侶璇';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '24', '陳侶璇' where not exists (select 1 from students where name='陳侶璇');
update students set class_id=(select id from classes where name='901'), seat_no='25' where name='盧品妍';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '25', '盧品妍' where not exists (select 1 from students where name='盧品妍');
update students set class_id=(select id from classes where name='901'), seat_no='27' where name='蘇云希';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '27', '蘇云希' where not exists (select 1 from students where name='蘇云希');
update students set class_id=(select id from classes where name='901'), seat_no='28' where name='林芯卉';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '28', '林芯卉' where not exists (select 1 from students where name='林芯卉');
update students set class_id=(select id from classes where name='901'), seat_no='29' where name='葉芷嫚';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '29', '葉芷嫚' where not exists (select 1 from students where name='葉芷嫚');
update students set class_id=(select id from classes where name='901'), seat_no='30' where name='楊月涵';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '30', '楊月涵' where not exists (select 1 from students where name='楊月涵');
update students set class_id=(select id from classes where name='901'), seat_no='31' where name='邱予樂';
insert into students (class_id, seat_no, name) select (select id from classes where name='901'), '31', '邱予樂' where not exists (select 1 from students where name='邱予樂');
update students set class_id=(select id from classes where name='902'), seat_no='02' where name='廖仙山';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '02', '廖仙山' where not exists (select 1 from students where name='廖仙山');
update students set class_id=(select id from classes where name='902'), seat_no='03' where name='沈伯霖';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '03', '沈伯霖' where not exists (select 1 from students where name='沈伯霖');
update students set class_id=(select id from classes where name='902'), seat_no='04' where name='廖靖智';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '04', '廖靖智' where not exists (select 1 from students where name='廖靖智');
update students set class_id=(select id from classes where name='902'), seat_no='05' where name='呂兆翔';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '05', '呂兆翔' where not exists (select 1 from students where name='呂兆翔');
update students set class_id=(select id from classes where name='902'), seat_no='07' where name='洪晟恩';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '07', '洪晟恩' where not exists (select 1 from students where name='洪晟恩');
update students set class_id=(select id from classes where name='902'), seat_no='08' where name='彭星翔';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '08', '彭星翔' where not exists (select 1 from students where name='彭星翔');
update students set class_id=(select id from classes where name='902'), seat_no='09' where name='張書禔';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '09', '張書禔' where not exists (select 1 from students where name='張書禔');
update students set class_id=(select id from classes where name='902'), seat_no='10' where name='簡伯錞';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '10', '簡伯錞' where not exists (select 1 from students where name='簡伯錞');
update students set class_id=(select id from classes where name='902'), seat_no='12' where name='蔡秉志';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '12', '蔡秉志' where not exists (select 1 from students where name='蔡秉志');
update students set class_id=(select id from classes where name='902'), seat_no='13' where name='黃晨恩';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '13', '黃晨恩' where not exists (select 1 from students where name='黃晨恩');
update students set class_id=(select id from classes where name='902'), seat_no='15' where name='蔡帛源';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '15', '蔡帛源' where not exists (select 1 from students where name='蔡帛源');
update students set class_id=(select id from classes where name='902'), seat_no='16' where name='陳艾妮';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '16', '陳艾妮' where not exists (select 1 from students where name='陳艾妮');
update students set class_id=(select id from classes where name='902'), seat_no='17' where name='徐薇茹';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '17', '徐薇茹' where not exists (select 1 from students where name='徐薇茹');
update students set class_id=(select id from classes where name='902'), seat_no='18' where name='范詠雁';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '18', '范詠雁' where not exists (select 1 from students where name='范詠雁');
update students set class_id=(select id from classes where name='902'), seat_no='19' where name='陳艾暐';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '19', '陳艾暐' where not exists (select 1 from students where name='陳艾暐');
update students set class_id=(select id from classes where name='902'), seat_no='20' where name='鄭仁靜';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '20', '鄭仁靜' where not exists (select 1 from students where name='鄭仁靜');
update students set class_id=(select id from classes where name='902'), seat_no='22' where name='羅翊軒';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '22', '羅翊軒' where not exists (select 1 from students where name='羅翊軒');
update students set class_id=(select id from classes where name='902'), seat_no='23' where name='游丹瑜';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '23', '游丹瑜' where not exists (select 1 from students where name='游丹瑜');
update students set class_id=(select id from classes where name='902'), seat_no='25' where name='楊小慶';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '25', '楊小慶' where not exists (select 1 from students where name='楊小慶');
update students set class_id=(select id from classes where name='902'), seat_no='26' where name='陳昕俞';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '26', '陳昕俞' where not exists (select 1 from students where name='陳昕俞');
update students set class_id=(select id from classes where name='902'), seat_no='28' where name='林昀靜';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '28', '林昀靜' where not exists (select 1 from students where name='林昀靜');
update students set class_id=(select id from classes where name='902'), seat_no='30' where name='林詩芸';
insert into students (class_id, seat_no, name) select (select id from classes where name='902'), '30', '林詩芸' where not exists (select 1 from students where name='林詩芸');

insert into exams (name, period, order_index) values ('九年級第一次模擬考', '九年級上學期', 10)
on conflict (name) do nothing;

insert into scores (student_id, exam_id, subject, score, level_text) values
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 21.0, '基礎／B'),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 25.0, '基礎／B'),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 28.0, '基礎／B'),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 2.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 10.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 34.0, '待加強／C'),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 1.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 17.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 14.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 44.961240310077514, '基礎／B'),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 2.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 3.0, null),
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.4, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 32.0, '基礎／B+'),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 46.0, '精熟／A+'),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 6.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 49.0, '精熟／A'),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 20.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 3.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 75.5, '基礎／B++'),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 4.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 39.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 92.55813953488372, '精熟／A'),
((select id from students where name='林楷程' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 35.0, '基礎／B++'),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 39.0, '基礎／B++'),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 45.0, '基礎／B++'),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 17.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 60.300000000000004, '基礎／B'),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 37.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 87.88482834994463, '基礎／B++'),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 3.0, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.4, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 27.0, '基礎／B'),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 43.0, '精熟／A'),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 5.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 40.0, '基礎／B++'),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 24.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 5.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 94.1, '精熟／A++'),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 7.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 37.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 87.88482834994463, '基礎／B++'),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 3.0, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.4, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 23.0, '基礎／B'),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 16.0, '待加強／C'),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 1.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 34.0, '基礎／B+'),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 9.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 33.099999999999994, '待加強／C'),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 1.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 26.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 67.41971207087487, '基礎／B'),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 2.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 3.0, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.4, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 34.0, '基礎／B++'),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 42.0, '精熟／A'),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 5.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 51.0, '精熟／A+'),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 6.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 24.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 3.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 89.1, '精熟／A+'),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 6.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 38.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 90.69767441860465, '精熟／A'),
((select id from students where name='賴東廷' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 31.0, '基礎／B+'),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 36.0, '基礎／B+'),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 11.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 3.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 44.9, '基礎／B'),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 32.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 78.58250276854928, '基礎／B+'),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 3.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 36.0, '精熟／A'),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 5.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 36.0, '基礎／B++'),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 47.0, '精熟／A'),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 17.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 60.300000000000004, '基礎／B'),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 37.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 87.88482834994463, '基礎／B++'),
((select id from students where name='簡廷諭' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 27.0, '基礎／B'),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 27.0, '基礎／B'),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 42.0, '基礎／B++'),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 15.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 51.0, '基礎／B'),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 32.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 18.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 76.67774086378738, '基礎／B+'),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 3.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 36.0, '精熟／A'),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 5.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 44.0, '精熟／A'),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 5.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 51.0, '精熟／A+'),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 6.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 19.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 67.1, '基礎／B+'),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 3.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 43.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 100.0, '精熟／A++'),
((select id from students where name='陳侶璇' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 35.0, '基礎／B++'),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 41.0, '基礎／B++'),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 46.0, '基礎／B++'),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 20.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 68.0, '基礎／B+'),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 3.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 94.4186046511628, '精熟／A'),
((select id from students where name='盧品妍' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 31.0, '基礎／B+'),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 36.0, '基礎／B++'),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 42.0, '基礎／B++'),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 17.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 57.800000000000004, '基礎／B'),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 38.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 89.7452934662237, '精熟／A'),
((select id from students where name='蘇云希' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 31.0, '基礎／B+'),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 38.0, '基礎／B++'),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 47.0, '精熟／A'),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 18.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 61.199999999999996, '基礎／B+'),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 3.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 18.0, null),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 91.56146179401993, '精熟／A'),
((select id from students where name='林芯卉' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 32.0, '基礎／B+'),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 25.0, '基礎／B'),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 41.0, '基礎／B++'),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 17.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 57.800000000000004, '基礎／B'),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 39.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 18.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 89.70099667774086, '精熟／A'),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 22.0, '基礎／B'),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 30.0, '基礎／B+'),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 3.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 36.0, '基礎／B+'),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 13.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 46.7, '基礎／B'),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 38.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 19.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 88.79291251384274, '基礎／B++'),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 33.0, '基礎／B++'),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 29.0, '基礎／B+'),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 3.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 36.0, '基礎／B+'),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 21.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 2.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 76.39999999999999, '基礎／B++'),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 4.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 37.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 18.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 85.98006644518271, '基礎／B++'),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 5.0, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.8, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 40.0, '精熟／A++'),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 7.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 48.0, '精熟／A++'),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 7.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 49.0, '精熟／A'),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 24.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 6.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 96.6, '精熟／A++'),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 7.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 43.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 100.0, '精熟／A++'),
((select id from students where name='廖仙山' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 36.0, '基礎／B++'),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 41.0, '基礎／B++'),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 22.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 74.8, '基礎／B++'),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 4.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 36.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 86.02436323366557, '基礎／B++'),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 3.0, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.4, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 24.0, '基礎／B'),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 24.0, '基礎／B'),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 34.0, '基礎／B+'),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 19.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 4.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 74.6, '基礎／B++'),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 4.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 29.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 15.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 68.23920265780731, '基礎／B'),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 2.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 28.0, '基礎／B'),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 38.0, '基礎／B+'),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 17.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 60.300000000000004, '基礎／B'),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 31.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 17.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 73.86489479512736, '基礎／B+'),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 3.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 3.0, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.4, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 37.0, '精熟／A'),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 5.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 32.0, '基礎／B+'),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 3.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 41.0, '基礎／B++'),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 16.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 56.9, '基礎／B'),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 41.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 96.27906976744187, '精熟／A+'),
((select id from students where name='洪晟恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 6.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 31.0, '基礎／B+'),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 3.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 45.0, '基礎／B++'),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 11.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 39.9, '基礎／B'),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 41.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 96.27906976744187, '精熟／A+'),
((select id from students where name='彭星翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 6.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 29.0, '基礎／B+'),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 41.0, '基礎／B++'),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 46.0, '基礎／B++'),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 23.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 80.7, '精熟／A'),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 5.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 43.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 100.0, '精熟／A++'),
((select id from students where name='張書禔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 28.0, '基礎／B'),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 44.0, '精熟／A'),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 5.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 52.0, '精熟／A++'),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 7.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 23.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 80.7, '精熟／A'),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 5.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 94.4186046511628, '精熟／A'),
((select id from students where name='簡伯錞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 34.0, '基礎／B++'),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 45.0, '精熟／A+'),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 6.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 50.0, '精熟／A'),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 24.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 6.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 96.6, '精熟／A++'),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 7.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 43.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 100.0, '精熟／A++'),
((select id from students where name='蔡秉志' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 31.0, '基礎／B+'),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 40.0, '基礎／B++'),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 4.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 40.0, '基礎／B++'),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 21.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 73.89999999999999, '基礎／B++'),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 4.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 36.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 19.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 85.07198228128462, '基礎／B++'),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 4.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 40.0, '精熟／A++'),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 7.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 49.0, '精熟／A++'),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 7.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 54.0, '精熟／A++'),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 7.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 23.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 6.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 93.2, '精熟／A++'),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 7.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 42.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 98.13953488372093, '精熟／A++'),
((select id from students where name='蔡帛源' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 29.0, '基礎／B+'),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 19.0, '基礎／B'),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 40.0, '基礎／B++'),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 6.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 3.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 27.9, '待加強／C'),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 1.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 38.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 90.69767441860465, '精熟／A'),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 5.0, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.8, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 34.0, '基礎／B++'),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 32.0, '基礎／B'),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 2.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 17.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 60.300000000000004, '基礎／B'),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 38.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 89.7452934662237, '精熟／A'),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 35.0, '基礎／B++'),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 46.0, '精熟／A+'),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 6.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 48.0, '精熟／A'),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 25.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 3.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 92.5, '精熟／A++'),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 7.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 43.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 99.04761904761905, '精熟／A++'),
((select id from students where name='范詠雁' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 31.0, '基礎／B+'),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 23.0, '基礎／B'),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 40.0, '基礎／B++'),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 11.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 39.9, '基礎／B'),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 26.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 18.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 65.51495016611295, '基礎／B'),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 2.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 32.0, '基礎／B+'),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 34.0, '基礎／B+'),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 3.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 39.0, '基礎／B+'),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 16.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 1.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 56.9, '基礎／B'),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 93.46622369878185, '精熟／A'),
((select id from students where name='鄭仁靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 23.0, '基礎／B'),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 24.0, '基礎／B'),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 34.0, '基礎／B+'),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 16.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 54.4, '基礎／B'),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 20.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 93.46622369878185, '精熟／A'),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 32.0, '基礎／B+'),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 3.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 42.0, '精熟／A'),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 5.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 46.0, '基礎／B++'),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 19.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 2.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 69.6, '基礎／B++'),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 4.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 42.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 98.13953488372093, '精熟／A++'),
((select id from students where name='游丹瑜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 7.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 37.0, '精熟／A'),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 5.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 28.0, '基礎／B'),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 43.0, '基礎／B++'),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 4.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 11.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 37.4, '待加強／C'),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 1.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 94.4186046511628, '精熟／A'),
((select id from students where name='楊小慶' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 26.0, '基礎／B'),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 34.0, '基礎／B+'),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 16.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 54.4, '基礎／B'),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 2.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 33.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 18.0, null),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 78.53820598006645, '基礎／B+'),
((select id from students where name='陳昕俞' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 3.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 27.0, '基礎／B'),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 2.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 23.0, '基礎／B'),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 2.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 35.0, '基礎／B+'),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 3.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 11.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 37.4, '待加強／C'),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 1.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 32.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 17.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 75.72535991140643, '基礎／B+'),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 3.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗級分', 4.0, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '寫作測驗加權分', 0.6, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考原始分）', 34.0, '基礎／B++'),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '國文（模考量尺分數）', 4.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考原始分）', 43.0, '精熟／A'),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '自然（模考量尺分數）', 5.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考原始分）', 47.0, '精熟／A'),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '社會（模考量尺分數）', 5.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考選擇題）', 24.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考非選擇題）', 0.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學', 81.6, '精熟／A'),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '數學（模考量尺分數）', 5.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英閱）', 40.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考英聽）', 21.0, null),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文', 94.4186046511628, '精熟／A'),
((select id from students where name='林詩芸' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), '英文（模考量尺分數）', 5.0, null)
on conflict (student_id, exam_id, subject) do update set score = excluded.score, level_text = excluded.level_text;

insert into exam_summary (student_id, exam_id, total_score, school_rank, class_rank) values
((select id from students where name='許育霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 9.4, null, null),
((select id from students where name='黃渟維' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 18.4, null, null),
((select id from students where name='黃壬辰' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 22.4, null, null),
((select id from students where name='倪楷崴' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 9.4, null, null),
((select id from students where name='邱柏諺' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 13.6, null, null),
((select id from students where name='陳禹彤' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 13.6, null, null),
((select id from students where name='葉芷嫚' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 16.6, null, null),
((select id from students where name='楊月涵' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 14.6, null, null),
((select id from students where name='邱予樂' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 18.8, null, null),
((select id from students where name='沈伯霖' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 18.4, null, null),
((select id from students where name='廖靖智' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 13.6, null, null),
((select id from students where name='呂兆翔' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 12.4, null, null),
((select id from students where name='黃晨恩' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 19.6, null, null),
((select id from students where name='陳艾妮' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 15.8, null, null),
((select id from students where name='徐薇茹' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 15.6, null, null),
((select id from students where name='陳艾暐' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 13.6, null, null),
((select id from students where name='羅翊軒' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 14.6, null, null),
((select id from students where name='林昀靜' order by id limit 1), (select id from exams where name='九年級第一次模擬考'), 11.6, null, null)
on conflict (student_id, exam_id) do update set total_score = excluded.total_score, school_rank = excluded.school_rank, class_rank = excluded.class_rank;
